import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import Nav from '@/components/ui/Nav/Nav'
import { ToastProvider } from '@/providers/toast-provider'


const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={`${inter.className}`}>

        <Nav />
        <ToastProvider />
     <div className='relative z-0 overflow-x-hidden'>
     {children}
     </div>
       
      </body>
    </html>
  )
}
